### ISSUE TITLE
API 10: Restore Archived Function Version Command

### ISSUE THREAD

**Issue by tony2-5** [tony2-5/osiris-function-library#10]
Problem: Implement the restoreArchivedVersion API, which restores an archived version of a function, making it available again.

Type: Function

Function Signature:

def restoreArchivedVersion(function_name: str, version: str) -> bool:
    pass

**Description:

**

    The restoreArchivedVersion API restores an archived function version and makes it available for use again.
    The restored version can be set as the active version if desired.

Input:

    function_name: The name of the function. (string)
    version: The archived version to restore. (string)

Output:

    True if the version is successfully restored, False otherwise.

Sample Input:

response = restoreArchivedVersion("addNumbers", "1.0")

Sample Output:

response = True

**Comment by mjkchoi1** [comment]
Pushed to Dev_MatthewChoi branch
