### ISSUE TITLE
API 9: Archive Function Version Command

### ISSUE THREAD

**Issue by tony2-5** [tony2-5/osiris-function-library#11]
Problem: Implement the archiveFunctionVersion API, which archives a function version to keep it inactive but accessible for future reference.

Type: Function

Function Signature:

def archiveFunctionVersion(function_name: str, version: str) -> bool:
pass

Description:

The archiveFunctionVersion API archives a specific version of a function, making it unavailable for use but still accessible in the system for reference or future rollback.

Input:

function_name: The name of the function. (string)
version: The version to archive. (string)

Output:

True if the version is successfully archived, False otherwise.

Sample Input:

response = archiveFunctionVersion("addNumbers", "1.0")

Sample Output:

response = True

**Comment by mjkchoi1** [comment]
Pushed to Dev_MatthewChoi branch
